# Generated by Django 5.2.7 on 2026-02-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
