# Generated by Django 5.2.7 on 2026-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_voter_voter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="father_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
