# Generated by Django 5.2.7 on 2026-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_votercorrection"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=200)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("voter_approved", "Voter Approved"),
                            ("voter_rejected", "Voter Rejected"),
                            ("voter_id_sent", "Voter ID Sent"),
                            ("correction_approved", "Correction Approved"),
                            ("correction_rejected", "Correction Rejected"),
                            ("new_election", "New Election"),
                            ("election_result", "Election Result"),
                            ("general", "General Update"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="voter",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
